Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Models/diarias_e_passagens.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diarias_e_passagens
    {
        public int id_diaria_passagem { get; set; }
        public int rgf { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_fim { get; set; }
        public string destino { get; set; }
        public string motivo { get; set; }
        public decimal valor { get; set; }
    
        public virtual servidores servidores { get; set; }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Controllers/diarias_e_passagensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using se_liga_mogi.Models;

namespace se_liga_mogi.Controllers
{
    public class diarias_e_passagensController : Controller
    {
        private Se_Liga_MogiEntities1 db = new Se_Liga_MogiEntities1();
        public ActionResult Index(
            int pagina = 1,
            string Pesquisa = "",
            int? Min = null,
            int? Max = null,
            DateTime? DataMin = null,
            DateTime? DataMax = null
        )

        {
            var q = db.diarias_e_passagens.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {
                q = q.Where(c => c.motivo.Contains(Pesquisa));
            }
            q = q.OrderBy(c => c.data_inicio);

            if (Min != 0) {
                q = q.Where(c => c.valor > Min);
            }

            if (Max != 0)
            {
                q = q.Where(c => c.valor < Min);
            }

            if (DataMin != DateTime.MinValue)
            {
                q = q.Where(c => c.data_inicio > DataMin);
            }

            if (DataMax != DateTime.MinValue)
            {
                q = q.Where(c => c.data_fim > DataMax);
            }
            
            ViewBag.Pesquisa = Pesquisa;
            ViewBag.Min = Min;
            ViewBag.Max = Max;
            ViewBag.DataMin = DataMin;
            ViewBag.DataMax = DataMax;
            return View(q.ToPagedList(pagina, 10));
        }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Controllers/servidoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using se_liga_mogi.Models;

namespace se_liga_mogi.Controllers
{
    public class servidoresController : Controller
    {
        private Se_Liga_MogiEntities1 db = new Se_Liga_MogiEntities1();
        public ActionResult Index(
            int pagina = 1,
            string Pesquisa = "",
            string Filtro = "",
            int? min = null,
            int? max = null)
        {
            var q = db.servidores.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {
                q = q.Where(c => c.nome_servidor.Contains(Pesquisa));
            }
            if (!string.IsNullOrEmpty(Filtro))
            {
                switch (Filtro)
                {
                    case "s":
                        if (min != null) {
                            q = q.Where(c => c.salario_servidor > min);
                        }
                        if (max != null) {
                            q = q.Where(c => c.salario_servidor < max);
                        }
                        q = q.OrderBy(c => c.salario_servidor);
                        break;
                    case "d":
                        if (min != null)
                        {
                            q = q.Where(c => c.descontos_servidor > min);
                        }
                        if (max != null)
                        {
                            q = q.Where(c => c.descontos_servidor < max);
                        }
                        q = q.OrderBy(c => c.descontos_servidor);
                        break;
                    case "r":
                        if (min != null)
                        {
                            q = q.Where(c => c.salario_liquido_servidor > min);
                        }
                        if (max != null)
                        {
                            q = q.Where(c => c.salario_liquido_servidor < max);
                        }
                        q = q.OrderBy(c => c.salario_liquido_servidor);
                        break;
                    default:
                        return HttpNotFound();
                }
            }
            q = q.OrderBy(c => c.rgf);
            ViewBag.Pesquisa = Pesquisa;
            ViewBag.Filtro = Filtro;
            ViewBag.Min = min;
            ViewBag.Max = max;
            return View(q.ToPagedList(pagina, 10));
        }
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            servidores servidores = db.servidores.Find(id);
            if (servidores == null)
            {
                return HttpNotFound();
            }
            return View(servidores);
        }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/diarias_e_passagens/Index.cshtml
@model PagedList.PagedList<se_liga_mogi.Models.diarias_e_passagens>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Diárias e passagens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Diarias e passagens</h2>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarColor03">
        @using (Html.BeginForm("Index", "servidores", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
        {
            <span style="margin-right: 10px">Buscar pelo Nome: </span>
            @Html.TextBox("Pesquisa", "", new { @class = "form-control mr-sm-2" })
            <span style="margin-right: 10px">Buscar por intervalo de: </span>
            <span style="margin-right: 10px">Valor mínimo: </span>
            @Html.TextBox("Min", "", new { @class = "form-control mr-sm-2", type = "number" })
            <span style="margin-right: 10px">Valor máximo: </span>
            @Html.TextBox("Max", "", new { @class = "form-control mr-sm-2", type = "number" })
            <span style="margin-right: 10px">Data mínima: </span>
            @Html.TextBox("DataMin", "", new { @class = "form-control mr-sm-2", type = "date" })
            <span style="margin-right: 10px">Data máxima: </span>
            @Html.TextBox("DataMax", "", new { @class = "form-control mr-sm-2", type = "date" })
            <button class="btn btn-info my-2 my-sm-0" type="submit" value="Pesquisar">Buscar</button>
        }
    </div>
</nav>

<table class="table">
    <tr>
        <th>
            Data Inicio
        </th>
        <th>
            Data Fim
        </th>
        <th>
            Destino
        </th>
        <th>
            Motivo
        </th>
        <th>
            Valor
        </th>
        <th>
            Nome do Servidor
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.data_inicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data_fim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.destino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.motivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.servidores.nome_servidor)
            </td>
        </tr>
    }

</table>

<div style="display:block; position:relative; width: 315px; left: calc(85% - 152px);">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, Pesquisa = ViewBag.Pesquisa, Min = ViewBag.Min, Max = ViewBag.Max, DataMin = ViewBag.DataMin, DataMax = ViewBag.DataMax }), new PagedListRenderOptions
    {
        DisplayLinkToFirstPage = PagedListDisplayMode.Never,
        DisplayLinkToLastPage = PagedListDisplayMode.Never,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        DisplayEllipsesWhenNotShowingAllPageNumbers = false
    })
</div>