Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Models/projetos_de_lei.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projetos_de_lei
    {
        public string numero_projeto { get; set; }
        public string autor_projeto { get; set; }
        public string assunto { get; set; }
        public string anotacao { get; set; }
        public string ano_projeto { get; set; }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Controllers/projetos_de_leiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using se_liga_mogi.Models;

namespace se_liga_mogi.Controllers
{
    public class projetos_de_leiController : Controller 
    {
        private Se_Liga_MogiEntities1 db = new Se_Liga_MogiEntities1();

        public ActionResult Index(int pagina = 1, 
            string Pesquisa = "", 
            string AnoFiltro = ""
            )
        {
            var q = db.projetos_de_lei.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {

                q = q.Where(c => c.numero_projeto.Contains(Pesquisa));
            }
            q = q.OrderBy(c => c.autor_projeto);

            if (!string.IsNullOrEmpty(AnoFiltro)) {
                q = q.Where(c => c.ano_projeto == AnoFiltro);
            }       

            int AnoAtual = DateTime.Now.Year;

            AnoAtual = AnoAtual - 2005; 

            List<SelectListItem> Anos = new List<SelectListItem>();

            for (int i = 0; i <= AnoAtual; i++) {
                string valor = (i + 2005).ToString();
                Anos.Add(new SelectListItem() { Text = valor, Value =valor });
            }

            SelectList AnosSelecao = new SelectList(Anos, "Text", "Value");

            ViewBag.Anos = AnosSelecao;
            ViewBag.CurrentSort = Pesquisa;
            return View(q.ToPagedList(pagina, 10));
        }
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            projetos_de_lei projetos_de_lei = db.projetos_de_lei.Find(id);
            if (projetos_de_lei == null)
            {
                return HttpNotFound();
            }
            return View(projetos_de_lei);
        }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/projetos_de_lei/Details.cshtml
@model se_liga_mogi.Models.projetos_de_lei

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>projetos_de_lei</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.autor_projeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.autor_projeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.anotacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anotacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.numero_projeto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/projetos_de_lei/Detalhes.cshtml
@model se_liga_mogi.Models.projetos_de_lei

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Detalhes dos servidores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Numero Projeto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero_projeto)
        </dd>

        <dt>
            Autor do Projeto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.autor_projeto)
        </dd>

        <dt>
            Assunto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assunto)
        </dd>

        <dt>
            Anotação        
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anotacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar à lista", "Index", "Home", new { area = "" }, new { @class = "btn btn-info btn-sm" })
</p>

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/projetos_de_lei/Index.cshtml
@model PagedList.PagedList<se_liga_mogi.Models.projetos_de_lei>

@using PagedList.Mvc;
<<<<<<< HEAD

@{
    ViewBag.Title = "Projetos de lei";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Projetos de lei</h2>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarColor03">
        @using (Html.BeginForm("Index", "projetos_de_lei", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
        {
            <span style="margin-right: 10px">Buscar pelo Nome: </span>
            @Html.TextBox("Pesquisa", "", new { @class = "form-control mr-sm-2" })
            <span style="margin-right: 10px">Buscar por ano: </span>
            @Html.DropDownList("AnoFiltro", (SelectList) ViewBag.Anos, "Selecione o ano...", new { @class = "form-inline my-2 my-lg-0" })
            <button class="btn btn-info my-2 my-sm-0" type="submit" value="Pesquisar">Buscar</button>
        }
    </div>
</nav>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table class="table">
    <tr class="table-info">
        <th>
            Nº Projeto
        </th>
        <th>
            Autor do Projeto
        </th>
        <th>
            Assunto
        </th>
        <th>
            Anotação
        </th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.autor_projeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.assunto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.anotacao)
        </td>
    </tr>
}

    @foreach (var item in Model)
    {
        <tr class="table-light">
            <td>
                @Html.DisplayFor(modelItem => item.numero_projeto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.autor_projeto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.assunto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.anotacao)
            </td>
            <td>
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.numero_projeto }, new { @class = "btn btn-info btn-sm" })
            </td>
        </tr>
    }

</table>

<div style="display:block; position:relative; width: 315px; left: calc(85% - 152px);">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, currentFilter = ViewBag.CurrentFilter, Pesquisa = ViewBag.Pesquisa }), new PagedListRenderOptions
    {
        DisplayLinkToFirstPage = PagedListDisplayMode.Never,
        DisplayLinkToLastPage = PagedListDisplayMode.Never,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        DisplayEllipsesWhenNotShowingAllPageNumbers = false
    })
</div>