Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Models/parlamentares.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parlamentares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parlamentares()
        {
            this.presenca_parlamentares = new HashSet<presenca_parlamentares>();
        }
    
        public int id_parlamentar { get; set; }
        public string nome_parlamentar { get; set; }
        public string cargo_parlamentar { get; set; }
        public int total_faltas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presenca_parlamentares> presenca_parlamentares { get; set; }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Controllers/parlamentaresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using se_liga_mogi.Models;

namespace se_liga_mogi.Controllers
{
    public class parlamentaresController : Controller
    {
        private Se_Liga_MogiEntities1 db = new Se_Liga_MogiEntities1();

        public ActionResult Index(int pagina = 1, string Pesquisa = "")
        {
            var q = db.parlamentares.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {
                q = q.Where(c => c.nome_parlamentar.Contains(Pesquisa));
            }
            q = q.OrderBy(c => c.nome_parlamentar);
            ViewBag.CurrentSort = Pesquisa;
            return View(q.ToPagedList(pagina, 10));
        }

        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            parlamentares parlamentares= db.parlamentares.Find(id);

            if (parlamentares == null)
            {
                return HttpNotFound();
            }

            return View(parlamentares);
        }
        public ActionResult Presenca(int pagina = 1)
        {
            var q = db.presenca_parlamentares.AsQueryable();
            return View(q.ToPagedList(pagina, 10));

            //presenca_parlamentares presenca = db.presenca_parlamentares.Find(id);
            //ViewBag.nomeParlamentar = parlamentares.nome_parlamentar;
            //return View(presenca);
        }
    }
}

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/parlamentares/Detalhes.cshtml
<<<<<<< HEAD
﻿@model se_liga_mogi.Models.parlamentares

=======
﻿@model IEnumerable<se_liga_mogi.Models.presenca_parlamentares>
>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c
@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<<<<<<< HEAD
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalhes</title>
</head>
<body>
    <div>
        <h4>Parlamentar</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Nome do parlamentar
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.nome_parlamentar)
            </dd>
    
            <dt>
                Cargo
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.cargo_parlamentar)
            </dd>
    
            <dt>
                Total de faltas
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.total_faltas)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Voltar à lista", "Index", "parlamentares", new { area = "" }, new { @class = "btn btn-info btn-sm" })
        @Html.ActionLink("Visualizar presenças, faltas e justificativas", "Presenca", "parlamentares", new { area = "" }, new { @class = "btn btn-info btn-sm" })
    </p>
</body>
</html>
=======

    <div>
        <h4>Detalhes dos parlamentar</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                Nome do servidor
            </dt>

            <dd>
                ViewBag.nomeParlamentar;
            </dd>


        </dl>

        <table class="table">

            <tr class="table-info">
                <th>
                    Data
                </th>
                <th>
                    Presente?
                </th>
                <th>
                    Motivo
                </th>
            </tr>

            @foreach (var item in Model)
            {
            <tr class="table-light">
                <td>
                    @Html.DisplayFor(modelItem => item.data_presenca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.falta_ou_nao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.motivo_da_falta)
                </td>
            </tr>
            }
        </table>
    </div>
<p>
    @Html.ActionLink("Voltar à lista", "Index", "Home", new { area = "" }, new { @class = "btn btn-info btn-sm" })
</p>

>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/parlamentares/Index.cshtml
@model PagedList.PagedList<se_liga_mogi.Models.parlamentares>

@using PagedList.Mvc;

@{
<<<<<<< HEAD
    ViewBag.Title = "Parlamentares";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <tr>
        <th>
            Nome do parlamentar
        </th>
        <th>
            Cargo
        </th>
        <th>
            Total de faltas
        </th>
=======
    ViewBag.Title = "Home Page";
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarColor03">
        @using (Html.BeginForm("Index", "parlamentares", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
        {
            <span style="margin-right: 10px">Buscar pelo Nome: </span>
            @Html.TextBox("Pesquisa", "", new { @class = "form-control mr-sm-2" })
            <button class="btn btn-info my-2 my-sm-0" type="submit" value="Pesquisar">Buscar</button>
        }
    </div>
</nav>

<table class="table">
    <tr class="table-info">
        <th>
            Nome do Parlamentar
        </th>
        <th>
            Cargo do Parlamentar
        </th>
        <th>
            Total de Faltas
        </th>
        <th></th>
>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c
    </tr>

    @foreach (var item in Model)
    {
<<<<<<< HEAD
        <tr>
=======
        <tr class="table-light">
>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c
            <td>
                @Html.DisplayFor(modelItem => item.nome_parlamentar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cargo_parlamentar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total_faltas)
            </td>
            <td>
<<<<<<< HEAD
                @Html.ActionLink("Edit", "Edit", new { id = item.id_parlamentar }) |
                @Html.ActionLink("Details", "Details", new { id = item.id_parlamentar }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id_parlamentar })
=======
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.id_parlamentar }, new { @class = "btn btn-info btn-sm" })
>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c
            </td>
        </tr>
    }

</table>
<<<<<<< HEAD
<div style="display:block; position:relative; width: 315px; left: calc(85% - 152px);">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, currentFilter = ViewBag.CurrentFilter, Pesquisa = ViewBag.Pesquisa }), new PagedListRenderOptions
    {
        DisplayLinkToFirstPage = PagedListDisplayMode.Never,
        DisplayLinkToLastPage = PagedListDisplayMode.Never,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        DisplayEllipsesWhenNotShowingAllPageNumbers = false
    })
</div>

=======

<div style="display:block; position:relative; width: 315px; left: calc(85% - 152px);">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, currentFilter = ViewBag.CurrentFilter, Pesquisa = ViewBag.Pesquisa }), new PagedListRenderOptions
{
    DisplayLinkToFirstPage = PagedListDisplayMode.Never,
    DisplayLinkToLastPage = PagedListDisplayMode.Never,
    DisplayLinkToNextPage = PagedListDisplayMode.Always,
    DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
    MaximumPageNumbersToDisplay = 5,
    DisplayEllipsesWhenNotShowingAllPageNumbers = false
})
</div>
>>>>>>> bba4e350deae07d0d0ec12c2673c737beec46a7c

Site Se Liga Mogi/se_liga_mogi - 1.0/se_liga_mogi/Views/parlamentares/Presenca.cshtml
@model IEnumerable<se_liga_mogi.Models.presenca_parlamentares>

@{
    ViewBag.Title = "Presenca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Presencas</h2>

<table class="table">
    <tr>
        <th>
            Data
        </th>
        <th>
            Presente?
        </th>
        <th>
            Motivo da falta: (Caso tenha faltado)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.data_presenca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.falta_ou_nao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.motivo_da_falta)
        </td>
    </tr>
}

</table>